### ISSUE TITLE
Specify URL via command line

### ISSUE THREAD

**Issue by nicrodgers** [B2F/Succss#5]
I'd like to be able to specify/override the URL for a given page configuration at runtime. 

I am writing Behat tests for a Drupal site.  Each time I create a new content type, I'll write a behat test that creates a new node and populates it with known data. I want to visually regression test changes to the layout of that example node.  

I can't re-use the same URL, because the node is created by Behat and destroyed at the end of each test session, so although the content and layout will be the same each run, the URL will be different.

Would it be possible to support this?

**Comment by SLyHuy** [comment]
Can you provide sample url what you want? And how is test flow?

**Comment by B2F** [comment]
You can share configuration properties from one page to another in various way, since the configuration file is a javasscript object. But why not just setting a consistent alias over node/{nid} ?

**Comment by nicrodgers** [comment]
@B2F Good idea about the alias. I will do that. Keep up the great work, guys!
